import type { Metadata } from "next";
import { Geist, Geist_Mono, Grenze } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const engravers = localFont({
  src: "../public/font/OPTIEngraversOldEnglish.otf",
  variable: "--font-engravers-old",
});

const grenze = Grenze({
  variable: "--font-grenze",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${engravers.variable} ${geistSans.variable} ${geistMono.variable} ${grenze.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
